version: '3'
services:
  react-app:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email kaban80@gmail.com --agree-tos --no-eff-email --force-renewal -d app.softeis.net -d www.app.softeis.net
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
